migratePlaylists = true
migrateStarred = true
mockMigration = false

[source]
host = "http://host"
port = 8080
username = "user"
password = "pass"
legacy = true

[target]
host = "http://host"
port = 8080
username = "user"
password = "pass"
legacy = false